apiVersion: policy/v1beta1
kind: PodSecurityPolicy
metadata:
  name: kyma.privileged
spec:
  privileged: true
  seLinux:
    rule: RunAsAny
  supplementalGroups:
    rule: RunAsAny
  runAsUser:
    rule: RunAsAny
  fsGroup:
    rule: RunAsAny
  volumes:
  - '*'
